apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  selector:
    matchLabels:
      app: apache
      department: apache
  replicas: 3
  template:
   metadata:
      labels:
        app: apache
        department: apache
   spec:
      containers:
      - name: hello
        image: lsluserd/apache:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
      name: my-np-service
spec:
      type: NodePort
      selector:
        app: apache
        department: apache
      ports:
      - protocol: TCP
        port: 80
        targetPort: 50000
